### ISSUE TITLE
Load occurrences only on click

### ISSUE THREAD

**Issue by RadLikeWhoa** [jfrehner/DocumentFinder#10]
Searching the content is actually pretty fast, it's displaying the occurrences which is rather slow. So if we only display the occurrences when some action is triggered, only the occurrences for one file could be loaded, which should be quite fast.

**Comment by AndreasGassmann** [comment]
This seems nice as a default behaviour (and is surprisingly fast). But I think I would still like the option to display a preview of all files because it's easier to get a fast overview of the content. Hovering over multiple documents takes quite a bit of time. What do you think?

**Comment by RadLikeWhoa** [comment]
Okay, we could:
- improve displayContent to be _a lot_ faster
- make some sort of option or shortcut to show all matches
- leave it like that as content search will probably a relatively minor thing at the assessment

Edit: we could also just defer the loading until the user has stopped entering text into the search bar. Sort of like a timeout. Most strings return only a couple of results so this could actually work.

**Comment by RadLikeWhoa** [comment]
I implemented the timeout method. In my tests it works fine, but there still might be some bugs. @AndreasGassmann @jfrehner can you guys test this properly?

**Comment by AndreasGassmann** [comment]
I'll test it when I get home tonight
